name: tbpt
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - adwaita-icon-theme=48.1=unix_0
  - anyio=4.10.0=pyhe01879c_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py39hd399759_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.38.0=h04ea711_2
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - boost-cpp=1.85.0=h44aadfe_2
  - brotli-python=1.1.0=py39hf88036b_3
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=h3faef2a_0
  - cffi=1.17.1=py39h15c3d72_0
  - comm=0.2.2=pyhd8ed1ab_1
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.14=py39hf88036b_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - epoxy=1.5.10=h166bdaf_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h36c2ea0_0
  - gdk-pixbuf=2.42.10=h64b468e_2
  - gettext=0.25.1=h5888daf_0
  - gettext-tools=0.25.1=h5888daf_0
  - giflib=5.2.2=hd590300_0
  - glib=2.80.2=hf974151_0
  - glib-tools=2.80.2=hb6ce0ca_0
  - graphite2=1.3.14=h5888daf_0
  - graphviz=12.2.1=h053244a_2
  - gtk3=3.24.37=hf583ffa_2
  - gts=0.7.6=h977cf35_4
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=7.3.0=h3d44ed6_1
  - hicolor-icon-theme=0.17=ha770c72_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.18.1=pyh707e725_3
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py39hf3d152e_1
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.2.6=pyhe01879c_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.16.0=pyhe01879c_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.6=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lark=1.2.2=pyhd8ed1ab_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h0aef613_1
  - libasprintf=0.25.1=h8e693c7_0
  - libasprintf-devel=0.25.1=h8e693c7_0
  - libboost=1.85.0=hba137d9_2
  - libboost-devel=1.85.0=h00ab1b0_2
  - libboost-headers=1.85.0=ha770c72_2
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.8.0=hca28451_1
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgd=2.3.3=h536bbd8_4
  - libgettextpo=0.25.1=h5888daf_0
  - libgettextpo-devel=0.25.1=h5888daf_0
  - libglib=2.80.2=hf974151_0
  - libgomp=14.2.0=h767d61c_2
  - libiconv=1.18=h4ce23a2_1
  - libltdl=2.4.3a=h5888daf_0
  - liblzma=5.8.1=hb9d3cd8_0
  - liblzma-devel=5.8.1=hb9d3cd8_0
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libpng=1.6.43=h2797004_0
  - librsvg=2.58.0=hce6bd6c_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtiff=4.7.0=hde9077f_0
  - libtool=2.5.4=h5888daf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=hd590300_1
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.12.7=hc051c1a_1
  - libzlib=1.2.13=h4ab18f5_6
  - markupsafe=3.0.2=py39h9399b63_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.3=pyh29332c3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - nspr=4.36=h5888daf_0
  - nss=3.100=hca3bf56_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.6.0=h26f9b46_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.50.14=heaa33ce_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.43=hcad00b1_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.2=h29eaf8c_0
  - platformdirs=4.3.7=pyh29332c3_0
  - poppler=24.09.0=hc52b300_2
  - poppler-data=0.4.12=hd8ed1ab_0
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py39h8cd3c5a_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pydot=1.4.1=py39h06a4308_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.15=hba424b6_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.9=7_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py39h9399b63_2
  - pyzmq=26.4.0=py39h4e4fb57_0
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.1.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.7=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - terminado=0.18.1=pyh0d859eb_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.2.1=pyhe01879c_2
  - tornado=6.4.2=py39h8cd3c5a_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250809=pyhd8ed1ab_0
  - typing-extensions=4.13.2=h0e9735f_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-compositeproto=0.4.2=hb9d3cd8_1002
  - xorg-damageproto=1.2.1=hb9d3cd8_1003
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=h0b41bf4_1
  - xorg-libxcursor=1.2.0=h0b41bf4_1
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h4bc722e_1
  - xorg-libxinerama=1.1.5=h27087fc_0
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxtst=1.2.5=h4bc722e_0
  - xorg-randrproto=1.5.0=hb9d3cd8_1002
  - xorg-recordproto=1.14.2=hb9d3cd8_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-util-macros=1.20.2=hb9d3cd8_0
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.8.1=hbcc6ac9_0
  - xz-gpl-tools=5.8.1=hbcc6ac9_0
  - xz-tools=5.8.1=hb9d3cd8_0
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py39hd399759_3
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - autograd==1.8.0
      - autograd-gamma==0.5.0
      - catboost==1.2.8
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - cloudpickle==3.1.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - fonttools==4.57.0
      - formulaic==1.2.0
      - fsspec==2025.3.2
      - huggingface-hub==0.30.2
      - imbalanced-learn==0.12.4
      - imblearn==0.0
      - importlib-resources==6.5.2
      - interface-meta==1.3.0
      - joblib==1.5.0
      - jsonschema==4.24.0
      - kiwisolver==1.4.7
      - lifelines==0.30.0
      - lightgbm==4.6.0
      - llvmlite==0.43.0
      - matplotlib==3.9.4
      - mpmath==1.3.0
      - narwhals==1.47.0
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openpyxl==3.1.5
      - pandas==2.2.3
      - patsy==1.0.1
      - pillow==11.2.1
      - plotly==6.2.0
      - python-graphviz==0.21
      - regex==2024.11.6
      - requests==2.32.3
      - rpds-py==0.26.0
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentence-transformers==4.1.0
      - shap==0.49.1
      - slicer==0.0.8
      - statsmodels==0.14.5
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      - torch==2.6.0
      - tqdm==4.67.1
      - transformers==4.51.3
      - triton==3.2.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - wrapt==1.17.2
      - xgboost==2.1.4
